### ISSUE TITLE
SSR is not working due to MutationObserver

### ISSUE THREAD

**Issue by kripod** [kitten/use-editable#5]
Hello,

Thank you for creating this wonderful package! Unfortunately, due to the nature of SSR, `MutationObserver` objects cannot be created on the server side:

https://github.com/kitten/use-editable/blob/33586136d9e0b8cd0cfabbc9a3a15f0808210236/src/useEditable.ts#L177

Changing the code above to `const observerRef = useRef(typeof window !== "undefined" ? new MutationObserver(addMutationsToQueue) : null);` could serve as an escape hatch.

**Comment by kitten** [comment]
Nice catch, mate! 🙌 sorry, I had another change locally which did already include this change, so I just pushed that up, since it also aims to make the state a little easier to deal with on my end, while I was playing around with some alternative `MutationObserver` timings

**Comment by kitten** [comment]
That's a pretty humble way of putting it! ❤️ If you're planning on using `useEditable` btw, let me know how it goes! It hasn't gotten much edge-case testing yet 😅

**Comment by kripod** [comment]
I've just tried using it for creating a single-line-only text editor which wraps when necessary. Unfortunately, character deletion in Firefox seems to be backwards. Also, when selecting some text and removing it, the change cannot be undone natively.

For now, I decided to go with [Slate](https://github.com/ianstormtaylor/slate) for building the first public version of [Copyfolio](https://www.copyfol.io/). However, we'll reconsider adopting `useEditable` as it gets more stable and supports basic validation (e.g. disallow pasting images). A tiny Slate-like wrapper around it would be a game changer. I wish I had some spare time to work on a side project like that 😄

**Comment by kitten** [comment]
@kripod yea, pasting I'll have to double check some edge cases for so that's 100% worth flagging as an issue if it's misbehaving :heart: it's something I've aggressively reduced code for, which may mean it isn't working right. Same for undo/redo although that's more solid. This can't really use native undo/redo (yet?) as that just goes against its logic too much..

The Firefox quirks I've dearly noticed. And they're really annoying. Chrome and Safari seem to be very smooth here, so Webkit in general I guess, but Firefox really hates deletions for some reason and those do work consistently, but are rather quirky-feeling depending on their timing. I haven't found a workaround for that yet
