### ISSUE TITLE
onSelect event is not firing in Chrome & Safari

### ISSUE THREAD

**Issue by ajilderda** [kitten/use-editable#7]
Hi @kitten, thanks for this useful hook!

I ran into an issue where the onSelect event is not firing in browsers that support `contenteditable="plaintext-only"` (like Chrome & Safari). This is due to the fact that [React only fires the onSelect event when `contenteditable="true"`](https://github.com/facebook/react/blob/993ca533b42756811731f6b7791ae06a35ee6b4d/packages/react-dom/src/events/plugins/SelectEventPlugin.js#L160).

I created a sandbox to demonstrate this (see console.log):
https://codesandbox.io/s/awesome-nightingale-s2gjb?file=/src/App.js
The above example works in Firefox (since it doesn't support `plaintext-only`).

This event would be handy to get the caret position when the user is navigating with the ← →-keys.

**Comment by kitten** [comment]
Hiya! You're always going to get the caret position and text data from the change handler that you pass to `useEditable`. Since the hook circumvents edits for React this is also more reliable.

This should fire on most events, but specifically on ones that change the caret position or change the editable's content.

**Comment by ajilderda** [comment]
Jup, onChange the caret position gets updated correctly, but not when you navigate with the ← →-keys. I understand the current implementation is sufficient in most cases, but since I need the caret position to be updated I've switched to Slate.js. Thanks anyways!
